name: Manage Secrets Requests

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (create, update)'
        required: true
        type: choice
        options:
          - Create New Secret
          - Delete a Secret
          - Add Key(s) in a Secret
          - Delete Key(s) in a Secret
          - Update Key(s) in a Secret
      tenant:
        description: 'Tenant name'
        required: true
        type: choice
        options:
          - gr
          - isl
          - pt
          - cz
          - al
          - ie
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - test
          - release
          - stage
          - production
      justification:
        description: 'Justification for the action'
        required: true
        type: string
      key:
        description: 'Key'
        required: true
        type: string
      value:
        description: 'Value'
        required: true
        type: string
     
     
     
      

jobs:
  manage-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment variables
      run: |
        echo "ACTION=${{ inputs.action }}" >> $GITHUB_ENV
        echo "TENANT=${{ inputs.tenant }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
        echo "JUSTIFICATION=${{ inputs.justification }}" >> $GITHUB_ENV
        echo "KEY=${{ inputs.key }}" >> $GITHUB_ENV
        echo "VALUE=${{ inputs.value }}" >> $GITHUB_ENV
     
      
       


    - name: Print Environment Variables
      run: |
        echo "Action: $ACTION"
        echo "Tenant: $TENANT"
        echo "Environment: $ENVIRONMENT"
        echo "Justification: $JUSTIFICATION"
        echo "Key: $KEY"
        echo "Value: $VALUE"
       
        
       

    - name: Create GitHub Issue
      id: create_issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const action = process.env.ACTION;
            const tenant = process.env.TENANT;
            const environment = process.env.ENVIRONMENT;
            const justification = process.env.JUSTIFICATION;
            const key = process.env.KEY;
            const value = process.env.VALUE;
            
           
           


            let issueTitle = `Secret Management: ${action} secret for ${tenant} in ${environment}`;
            let issueBody = `
            ## Secret Management Request

            **Action:** ${action}

            **Tenant:** ${tenant}

            **Environment:** ${environment}

            **Justification:** ${justification}

            - Key: ${key}
            - Value: ${value}
            
            
            `;

            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              assignees: ['mohamedkhames2222@gmail.com'],
              labels: ['ToDo']
            });

            core.setOutput('issue_url', issue.data.html_url);
          } catch (error) {
            core.setFailed(`Error: ${error.message}`);
          }

    - name: Output Issue URL
      run: |
        echo "Issue created: ${{ steps.create_issue.outputs.issue_url }}"
